In [1]:
import os

import numpy as numpy
import pandas as pd

In [2]:
csv_files = [
    os.path.join("raw_data", "mega_cap_stocks.csv"),
    os.path.join("raw_data", "large_cap_stocks.csv"),
    os.path.join("raw_data", "mid_cap_stocks.csv"),
    os.path.join("raw_data", "small_cap_stocks.csv"),
    os.path.join("raw_data", "micro_cap_stocks.csv"),
    os.path.join("raw_data", "nano_cap_stocks.csv"),
]

dataframes = [pd.read_csv(file) for file in csv_files]
stock_df = pd.concat(dataframes, ignore_index=True)

stock_df.head()

,symbol,company_name,market_cap_category,price,market_cap,revenue_ttm,net_income_ttm,shares_out,eps_ttm,pe_ratio,...,days_range,fifty_two_week_range,beta,analysts,price_target,earnings_date,industry,sector,ipo_date,stock_exchange
0,AAPL,Apple Inc.,Mega-Cap,244.60,3.67T,395.76B,96.15B,15.02B,6.28,38.95,...,241.00 - 245.41,164.08 - 260.10,1.20,Buy,242.36 (-0.92%),"Jan 30, 2025",Consumer Electronics,Technology,"Dec 12, 1980",NASDAQ
1,NVDA,NVIDIA Corporation,Mega-Cap,138.85,3.40T,113.27B,63.07B,24.49B,2.53,54.83,...,135.50 - 139.19,66.25 - 153.13,1.62,Strong Buy,169.53 (+22.1%),"Feb 26, 2025",Semiconductors,Technology,"Jan 22, 1999",NASDAQ
2,MSFT,Microsoft Corporation,Mega-Cap,408.43,3.04T,261.80B,92.75B,7.43B,12.41,32.91,...,405.90 - 408.83,385.58 - 468.35,0.89,Strong Buy,510.41 (+24.97%),"Jan 29, 2025",Software - Infrastructure,Technology,"Mar 13, 1986",NASDAQ
3,AMZN,"Amazon.com, Inc.",Mega-Cap,228.68,2.42T,637.96B,59.25B,10.60B,5.53,41.35,...,227.23 - 229.79,151.61 - 242.52,1.16,Strong Buy,262.70 (+14.88%),"Feb 6, 2025",Internet Retail,Consumer Discretionary,"May 15, 1997",NASDAQ
4,GOOGL,Alphabet Inc.,Mega-Cap,185.23,2.26T,350.02B,100.12B,12.19B,8.04,23.03,...,184.32 - 186.40,130.67 - 207.05,0.99,Buy,212.79 (+14.88%),"Feb 4, 2025",Internet Content & Information,Communication Services,"Aug 19, 2004",NASDAQ

In [3]:
stock_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   symbol                300 non-null    object
 1   company_name          300 non-null    object
 2   market_cap_category   300 non-null    object
 3   price                 300 non-null    object
 4   market_cap            300 non-null    object
 5   revenue_ttm           279 non-null    object
 6   net_income_ttm        294 non-null    object
 7   shares_out            295 non-null    object
 8   eps_ttm               293 non-null    float64
 9   pe_ratio              207 non-null    float64
 10  forward_pe            197 non-null    float64
 11  dividend              155 non-null    object
 12  ex_dividend_date      155 non-null    object
 13  volume                299 non-null    object
 14  average_volume        0 non-null      float64
 15  open                  300 non-null    object
 16  previous_close        300 non-null    object
 17  days_range            300 non-null    object
 18  fifty_two_week_range  300 non-null    object
 19  beta                  271 non-null    float64
 20  analysts              236 non-null    object
 21  price_target          231 non-null    object
 22  earnings_date         282 non-null    object
 23  industry              300 non-null    object
 24  sector                300 non-null    object
 25  ipo_date              300 non-null    object
 26  stock_exchange        300 non-null    object
dtypes: float64(5), object(22)
memory usage: 406.7 KB

In [4]:
stock_df.columns

Index(['symbol', 'company_name', 'market_cap_category', 'price', 'market_cap',
       'revenue_ttm', 'net_income_ttm', 'shares_out', 'eps_ttm', 'pe_ratio',
       'forward_pe', 'dividend', 'ex_dividend_date', 'volume',
       'average_volume', 'open', 'previous_close', 'days_range',
       'fifty_two_week_range', 'beta', 'analysts', 'price_target',
       'earnings_date', 'industry', 'sector', 'ipo_date', 'stock_exchange'],
      dtype='object')

In [5]:
stock_df.drop(
    columns=[
        "shares_out",
        "dividend",
        "ex_dividend_date",
        "average_volume",
        "analysts",
        "price_target",
        "earnings_date",
        "ipo_date",
        "stock_exchange",
    ],
    inplace=True,
)

In [6]:
stock_df.columns

Index(['symbol', 'company_name', 'market_cap_category', 'price', 'market_cap',
       'revenue_ttm', 'net_income_ttm', 'eps_ttm', 'pe_ratio', 'forward_pe',
       'volume', 'open', 'previous_close', 'days_range',
       'fifty_two_week_range', 'beta', 'industry', 'sector'],
      dtype='object')

In [7]:
stock_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   symbol                300 non-null    object
 1   company_name          300 non-null    object
 2   market_cap_category   300 non-null    object
 3   price                 300 non-null    object
 4   market_cap            300 non-null    object
 5   revenue_ttm           279 non-null    object
 6   net_income_ttm        294 non-null    object
 7   eps_ttm               293 non-null    float64
 8   pe_ratio              207 non-null    float64
 9   forward_pe            197 non-null    float64
 10  volume                299 non-null    object
 11  open                  300 non-null    object
 12  previous_close        300 non-null    object
 13  days_range            300 non-null    object
 14  fifty_two_week_range  300 non-null    object
 15  beta                  271 non-null    float64
 16  industry              300 non-null    object
 17  sector                300 non-null    object
dtypes: float64(4), object(14)
memory usage: 264.2 KB

In [8]:
stock_df["market_cap_category"] = stock_df.market_cap_category.astype("category")

In [9]:
stock_df["price"] = stock_df.price.replace(",", "", regex=True).astype("float")

In [10]:
multiplier = {"T": 1e12, "B": 1e9, "M": 1e6, "K": 1e3}


def convert_to_float(x):
    if isinstance(x, str):
        # Check if the last character is one of the suffix letters
        if x[-1].upper() in multiplier:
            return float(x[:-1].replace(",", ".")) * multiplier[x[-1].upper()]
        else:
            return float(x.replace(",", "."))
    return x

In [11]:
# Convert the 'market_cap' column
stock_df["market_cap"] = stock_df.market_cap.apply(convert_to_float)

# Convert the 'revenue_ttm' column
stock_df["revenue_ttm"] = stock_df.revenue_ttm.apply(convert_to_float)

# Convert the 'net_income_ttm' column
stock_df["net_income_ttm"] = stock_df.net_income_ttm.apply(convert_to_float)

In [12]:
# Convert the 'volume' column to float
stock_df['volume'] = stock_df.volume.str.replace(',', '', regex=True).astype(float)

# Convert the 'open' column to float
stock_df['open'] = stock_df.open.str.replace(',', '', regex=True).astype(float)

# Convert the 'previous_close' column to float
stock_df['previous_close'] = stock_df.previous_close.str.replace(',', '', regex=True).astype(float)

In [13]:
# For the days_range column:
# Split the string into two parts, remove extra spaces and commas, then convert to float
stock_df[['days_range_min', 'days_range_max']] = stock_df['days_range'].str.split('-', expand=True)
stock_df['days_range_min'] = stock_df['days_range_min'].str.strip().str.replace(',', '', regex=False).astype(float)
stock_df['days_range_max'] = stock_df['days_range_max'].str.strip().str.replace(',', '', regex=False).astype(float)

In [14]:
# For the fifty_two_week_range column:
# Split the string into two parts, remove extra spaces and commas, then convert to float
stock_df[['fifty_two_week_range_min', 'fifty_two_week_range_max']] = stock_df['fifty_two_week_range'].str.split('-', expand=True)
stock_df['fifty_two_week_range_min'] = stock_df['fifty_two_week_range_min'].str.strip().str.replace(',', '', regex=False).astype(float)
stock_df['fifty_two_week_range_max'] = stock_df['fifty_two_week_range_max'].str.strip().str.replace(',', '', regex=False).astype(float)

In [15]:
# Remove the original range columns
stock_df.drop(columns=['days_range', 'fifty_two_week_range'], inplace=True)

In [16]:
stock_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   symbol                    300 non-null    object
 1   company_name              300 non-null    object
 2   market_cap_category       300 non-null    category
 3   price                     300 non-null    float64
 4   market_cap                300 non-null    float64
 5   revenue_ttm               279 non-null    float64
 6   net_income_ttm            294 non-null    float64
 7   eps_ttm                   293 non-null    float64
 8   pe_ratio                  207 non-null    float64
 9   forward_pe                197 non-null    float64
 10  volume                    299 non-null    float64
 11  open                      100 non-null    float64
 12  previous_close            100 non-null    float64
 13  beta                      271 non-null    float64
 14  industry                  300 non-null    object
 15  sector                    300 non-null    object
 16  days_range_min            300 non-null    float64
 17  days_range_max            300 non-null    float64
 18  fifty_two_week_range_min  300 non-null    float64
 19  fifty_two_week_range_max  300 non-null    float64
dtypes: category(1), float64(15), object(4)
memory usage: 119.6 KB

In [17]:
stock_df.head()

,symbol,company_name,market_cap_category,price,market_cap,revenue_ttm,net_income_ttm,eps_ttm,pe_ratio,forward_pe,volume,open,previous_close,beta,industry,sector,days_range_min,days_range_max,fifty_two_week_range_min,fifty_two_week_range_max
0,AAPL,Apple Inc.,Mega-Cap,244.60,3.670000e+12,3.957600e+11,9.615000e+10,6.28,38.95,32.44,40145605.0,241.07,241.53,1.20,Consumer Electronics,Technology,241.00,245.41,164.08,260.10
1,NVDA,NVIDIA Corporation,Mega-Cap,138.85,3.400000e+12,1.132700e+11,6.307000e+10,2.53,54.83,35.42,194448420.0,136.41,135.29,1.62,Semiconductors,Technology,135.50,139.19,66.25,153.13
2,MSFT,Microsoft Corporation,Mega-Cap,408.43,3.040000e+12,2.618000e+11,9.275000e+10,12.41,32.91,29.58,21799548.0,407.65,410.54,0.89,Software - Infrastructure,Technology,405.90,408.83,385.58,468.35
3,AMZN,"Amazon.com, Inc.",Mega-Cap,228.68,2.420000e+12,6.379600e+11,5.925000e+10,5.53,41.35,36.17,26365555.0,229.22,230.37,1.16,Internet Retail,Consumer Discretionary,227.23,229.79,151.61,242.52
4,GOOGL,Alphabet Inc.,Mega-Cap,185.23,2.260000e+12,3.500200e+11,1.001200e+11,8.04,23.03,20.61,20390327.0,185.05,186.14,0.99,Internet Content & Information,Communication Services,184.32,186.40,130.67,207.05

In [18]:
file_path = os.path.join('clean_data', 'stocks.csv')

stock_df.to_csv(file_path, index=False)

---